import type { TypeKey } from '../c4'

// What each type is actually built from. The brand set knows 3,453 products and
// nothing about which is a database, so this is the one thing it cannot tell
// us: the shortlist a type offers before you have typed anything. Curated, so
// it is short and right rather than long and sorted alphabetically.

// A name here is written the way the brand set titles it, so the mark lands —
// "Apache Kafka", not "Kafka"; "Timescale", not "TimescaleDB". A product the
// brand set does not carry (Amazon pulled its own in 2024, and Java, gRPC and
// HAProxy were never in it) is still a good row; it just stands bare.

// Every type takes a line, so a type added without one is a compile error, and
// the two that have no technology at all say so in the open: a person is a job,
// a software system is C4's black box.
export const TECH: Record<TypeKey, string[]> = {
  // Actors & Externals
  person: [],
  system: [],

  // Applications
  container: ['Go', 'Java', 'Python', 'Node.js', 'TypeScript', 'Rust', 'Ruby', 'PHP', '.NET'],
  component: ['Go', 'Java', 'Python', 'TypeScript', 'Kotlin', 'Rust', 'C#'],
  'web-app': ['Next.js', 'Ruby on Rails', 'Django', 'Laravel', 'Spring', 'Nuxt', 'ASP.NET Core'],
  'single-page-app': ['React', 'Vue.js', 'Angular', 'Svelte', 'SolidJS', 'Ember.js', 'HTMX'],
  'mobile-app': ['Swift', 'Kotlin', 'React Native', 'Flutter', 'Expo', 'Ionic', 'Capacitor'],
  'desktop-app': ['Electron', 'Tauri', 'Qt', 'Flutter', 'Swift', 'GTK', '.NET'],
  'api-service': ['Go', 'Spring', 'FastAPI', 'Express', 'NestJS', 'ASP.NET Core', 'Ruby on Rails'],
  'serverless-function': [
    'AWS Lambda',
    'Google Cloud Run',
    'Cloudflare Workers',
    'Azure Functions',
    'Vercel',
    'Netlify',
    'Deno',
  ],
  worker: ['Sidekiq', 'Celery', 'BullMQ', 'Apache Kafka', 'RabbitMQ', 'Temporal', 'Faust'],
  'scheduled-job': [
    'cron',
    'Kubernetes CronJob',
    'Amazon EventBridge Scheduler',
    'Apache Airflow',
    'Temporal',
    'Quartz',
  ],
  'batch-job': ['Apache Spark', 'dbt', 'Apache Airflow', 'AWS Glue', 'Databricks', 'Apache Flink'],

  // APIs & Contracts
  'rest-api': ['OpenAPI', 'Swagger', 'JSON', 'JSON:API', 'HAL'],
  'graphql-api': ['GraphQL', 'Apollo GraphQL', 'Hasura', 'Relay', 'Strawberry', 'Prisma'],
  'grpc-service': ['gRPC', 'Protobuf', 'Buf', 'Connect'],
  'websocket-channel': [
    'Socket.io',
    'Phoenix Framework',
    'SignalR',
    'Ably',
    'Pusher',
    'Centrifugo',
  ],
  webhook: ['HTTP', 'Svix', 'Hookdeck', 'Zapier', 'Stripe'],
  'server-sent-events': ['HTTP', 'text/event-stream', 'Mercure'],
  'soap-service': ['WSDL', 'XML', 'Apache CXF', 'Spring'],
  'event-contract': ['AsyncAPI', 'Apache Avro', 'Protobuf', 'JSON Schema', 'Schema Registry'],

  // Data Stores
  'relational-db': [
    'PostgreSQL',
    'MySQL',
    'MariaDB',
    'Microsoft SQL Server',
    'Oracle',
    'SQLite',
    'CockroachDB',
    'Amazon Aurora',
    'Supabase',
    'Neon',
  ],
  'document-db': [
    'MongoDB',
    'Couchbase',
    'Apache CouchDB',
    'Firebase',
    'Amazon DocumentDB',
    'RavenDB',
    'ArangoDB',
  ],
  'key-value-store': [
    'Redis',
    'Amazon DynamoDB',
    'etcd',
    'Valkey',
    'Memcached',
    'Hazelcast',
    'Aerospike',
  ],
  'wide-column-store': [
    'Apache Cassandra',
    'ScyllaDB',
    'Google Bigtable',
    'Apache HBase',
    'Amazon Keyspaces',
  ],
  'graph-db': ['Neo4j', 'Amazon Neptune', 'ArangoDB', 'Dgraph', 'JanusGraph', 'Memgraph'],
  'timeseries-db': [
    'InfluxDB',
    'Timescale',
    'Prometheus',
    'ClickHouse',
    'VictoriaMetrics',
    'QuestDB',
    'Amazon Timestream',
  ],
  'vector-db': ['pgvector', 'Pinecone', 'Qdrant', 'Weaviate', 'Milvus', 'Chroma', 'Redis'],
  'search-index': [
    'Elasticsearch',
    'OpenSearch',
    'Typesense',
    'Algolia',
    'Meilisearch',
    'Apache Solr',
  ],
  'object-store': [
    'Amazon S3',
    'Google Cloud Storage',
    'Azure Blob Storage',
    'MinIO',
    'Cloudflare R2',
    'Backblaze',
  ],
  'file-system': ['NFS', 'Amazon EFS', 'Amazon FSx', 'Ceph', 'ZFS', 'GlusterFS'],
  'data-warehouse': [
    'Snowflake',
    'Google BigQuery',
    'Amazon Redshift',
    'Databricks',
    'ClickHouse',
    'Teradata',
  ],
  'data-lake': ['Apache Iceberg', 'Apache Hudi', 'Amazon S3', 'Databricks', 'Apache Hadoop'],

  // Caching
  'memory-cache': ['Redis', 'Memcached', 'Valkey', 'Hazelcast', 'Dragonfly', 'Caffeine'],
  'distributed-cache': [
    'Redis',
    'Hazelcast',
    'Apache Ignite',
    'Amazon ElastiCache',
    'Couchbase',
    'Valkey',
  ],
  'client-cache': [
    'TanStack Query',
    'SWR',
    'Apollo GraphQL',
    'Workbox',
    'Service Worker',
    'RTK Query',
  ],
  'read-replica': ['PostgreSQL', 'MySQL', 'Amazon Aurora', 'MongoDB', 'Redis', 'MariaDB'],

  // Messaging & Streaming
  'message-queue': [
    'RabbitMQ',
    'Amazon SQS',
    'Apache ActiveMQ',
    'Azure Service Bus',
    'NATS',
    'IBM MQ',
    'Redis',
  ],
  'pubsub-topic': [
    'Google Pub/Sub',
    'Amazon SNS',
    'Redis',
    'NATS',
    'MQTT',
    'Azure Event Grid',
    'Apache Pulsar',
  ],
  'event-stream': [
    'Apache Kafka',
    'Amazon Kinesis',
    'Redpanda',
    'Apache Pulsar',
    'Confluent',
    'Azure Event Hubs',
    'NATS JetStream',
  ],
  'event-bus': [
    'Amazon EventBridge',
    'NATS',
    'Apache Kafka',
    'Azure Event Grid',
    'Google Pub/Sub',
    'RabbitMQ',
  ],
  'task-queue': ['Celery', 'Sidekiq', 'BullMQ', 'Temporal', 'Resque', 'Hangfire', 'Apache Airflow'],
  'dead-letter-queue': [
    'Amazon SQS',
    'RabbitMQ',
    'Apache Kafka',
    'Azure Service Bus',
    'Google Pub/Sub',
  ],
  'change-data-capture': [
    'Debezium',
    'Apache Kafka',
    'AWS DMS',
    'Fivetran',
    'Airbyte',
    'PostgreSQL',
  ],

  // Edge & Traffic
  dns: ['Cloudflare', 'Amazon Route 53', 'Google Cloud DNS', 'Akamai', 'CoreDNS', 'BIND'],
  cdn: ['Cloudflare', 'Amazon CloudFront', 'Fastly', 'Akamai', 'Vercel', 'Netlify', 'Bunny'],
  'load-balancer': [
    'NGINX',
    'HAProxy',
    'AWS ELB',
    'Envoy Proxy',
    'Traefik Proxy',
    'Google Cloud Load Balancing',
  ],
  'reverse-proxy': [
    'NGINX',
    'Envoy Proxy',
    'Traefik Proxy',
    'Caddy',
    'HAProxy',
    'Apache HTTP Server',
  ],
  'api-gateway': [
    'Kong',
    'Amazon API Gateway',
    'Apigee',
    'Traefik Proxy',
    'Tyk',
    'KrakenD',
    'Envoy Proxy',
  ],
  'service-mesh': ['Istio', 'Linkerd', 'Consul', 'Cilium', 'Envoy Proxy', 'AWS App Mesh', 'Kuma'],
  waf: ['Cloudflare', 'AWS WAF', 'Akamai', 'Fastly', 'ModSecurity', 'Imperva'],
  'ingress-controller': ['NGINX', 'Traefik Proxy', 'HAProxy', 'Istio', 'Kong', 'Gateway API'],

  // Platform & Security
  'identity-provider': [
    'Okta',
    'Auth0',
    'Microsoft Entra ID',
    'Keycloak',
    'Clerk',
    'WorkOS',
    'Ping Identity',
  ],
  'auth-service': ['Keycloak', 'Auth0', 'Supabase', 'Firebase', 'Clerk', 'Ory', 'Auth.js'],
  'secrets-manager': [
    'HashiCorp Vault',
    'AWS Secrets Manager',
    'Azure Key Vault',
    'Doppler',
    'Infisical',
    '1Password',
  ],
  'kms-certificates': [
    "Let's Encrypt",
    'AWS KMS',
    'cert-manager',
    'HashiCorp Vault',
    'Azure Key Vault',
    'Google Cloud KMS',
  ],
  'policy-service': ['Open Policy Agent', 'Cedar', 'SpiceDB', 'Casbin', 'Oso', 'Keycloak'],
  'service-registry': ['Consul', 'etcd', 'Apache ZooKeeper', 'Eureka', 'Kubernetes', 'CoreDNS'],
  'config-service': [
    'Consul',
    'etcd',
    'AWS AppConfig',
    'Spring Cloud Config',
    'Apache ZooKeeper',
    'Doppler',
  ],
  'feature-flag-service': [
    'LaunchDarkly',
    'Unleash',
    'Flagsmith',
    'PostHog',
    'Statsig',
    'ConfigCat',
    'Split',
  ],

  // Observability & Ops
  'metrics-store': [
    'Prometheus',
    'Datadog',
    'Grafana',
    'New Relic',
    'InfluxDB',
    'Dynatrace',
    'Amazon CloudWatch',
  ],
  'log-aggregator': [
    'Grafana Loki',
    'Elasticsearch',
    'Splunk',
    'Datadog',
    'Fluentd',
    'Graylog',
    'Amazon CloudWatch',
  ],
  'tracing-backend': [
    'Jaeger',
    'OpenTelemetry',
    'Grafana Tempo',
    'Zipkin',
    'Datadog',
    'Honeycomb',
    'New Relic',
  ],
  alerting: ['PagerDuty', 'Opsgenie', 'Grafana', 'Prometheus', 'Slack', 'incident.io'],
  'cicd-pipeline': [
    'GitHub Actions',
    'GitLab CI',
    'Jenkins',
    'Argo CD',
    'CircleCI',
    'Buildkite',
    'Tekton',
  ],

  // Analytics & ML
  'stream-processor': [
    'Apache Flink',
    'Kafka Streams',
    'Apache Spark',
    'Materialize',
    'Apache Beam',
    'ksqlDB',
  ],
  'batch-processor': [
    'Apache Spark',
    'dbt',
    'Apache Hadoop',
    'AWS Glue',
    'Databricks',
    'Apache Beam',
  ],
  'inference-endpoint': [
    'Amazon SageMaker',
    'NVIDIA Triton',
    'vLLM',
    'TensorFlow',
    'PyTorch',
    'Hugging Face',
    'ONNX',
  ],
  'training-pipeline': [
    'Kubeflow',
    'PyTorch',
    'TensorFlow',
    'Ray',
    'MLflow',
    'Vertex AI',
    'Weights & Biases',
  ],
  'feature-store': ['Feast', 'Tecton', 'Databricks', 'Amazon SageMaker', 'Hopsworks', 'Vertex AI'],
  'llm-service': [
    'Anthropic',
    'OpenAI',
    'Google Gemini',
    'Ollama',
    'Hugging Face',
    'Mistral AI',
    'Amazon Bedrock',
    'vLLM',
  ],

  // Boundaries & Zones — a frame is a name and a reason, and fields.ts gives
  // the whole shelf no technology row to fill. The lines stand anyway, because
  // a type without one is the compile error that keeps this table honest.
  enterprise: [],
  'system-boundary': [],
  'container-boundary': [],
  domain: [],
  'trust-zone': [],
  team: [],
}
